server:
  port: 8080

spring:
  profiles:
    active: prod
  application:
    name: boozeandice
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true
  pid:
    fail-on-write-error: true
    file: ./logs/boozeandicepos.pid
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      pool-name: BoozeandiceHikariPool
      connection-test-query: select 1 from dual
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000 


#application settings
business_name: Booze and Ice Store
business_address: PUERTO GALLERA ORIENTAL MINDORO
senior_citizen_discount: 0.20 #20 PERCENT SENIOR CITIZEN DISCOUNT
available_tables: 6
schema_name: boozeandice
export_import_script: file:C:\Projects\boozeandicepos\boozeandice-pos\boozeandice\boozeandice-pos\resources\export_import_script.bat
database-sync:
  status: 'OFF'

#img upload location
upload:
  product:
    directory: C:\Projects\boozeandicepos\boozeandice-pos\boozeandice\boozeandice-pos\img\products
  profile:
    directory: C:\Projects\boozeandicepos\boozeandice-pos\boozeandice\boozeandice-pos\img\profile
  barcode:
    directory: C:\Projects\boozeandicepos\boozeandice-pos\boozeandice\boozeandice-pos\img\barcodes
  
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
    com:
      boozeandice: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%p %thread %F:%L] %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%p %thread %F:%L] %msg%n'
  file:
    path: 'C:\workspace\loggers\boozeandice'
    name: '${logging.file.path}/${spring.profiles.active}.${spring.application.name}-${date:yyyy-MM-dd}.log'

---
 
spring: 
  config:
    activate:
      on-profile: dev
  datasource: 
    url: jdbc:mysql://localhost:3306/boozeandice
    username: root
    password: lxbordo
  #cloud-datasource:
    #url: jdbc:mysql://boozeandice-test-rds.c7l9gtvaasvy.ap-southeast-1.rds.amazonaws.com:3306/boozeandice
    #username: admin
    #password: bait-micke
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate-ddl: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    hibernate:
      ddl-auto: update
  cache:
    type: simple
 
---
spring:  
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://boozeandice-test-rds.c7l9gtvaasvy.ap-southeast-1.rds.amazonaws.com:3306/boozeandice
    username: admin
    password: bait-micke   
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate-ddl: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    hibernate:
      ddl-auto: update
  cache:
    type: simple     